name: dice
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.7 <3.0.0'

dependencies:
  d20: <1.0.0
  args: any 

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
